### ISSUE TITLE
Order of h4/p tags causing problems!

### ISSUE THREAD

**Issue by jessipearcy** [learn-co-curriculum/icebreakers-homepage-html-lab#1]
It would be awesome to make sure the ReadMe lets the reader know that they need to add the h4 and p tags in a particular order if they'd like to pass the tests. Code in the `main` section needs to read:

```<main>
      <div>
        <h1>Let's get started!</h1>
        <p>This site will generate some icebreaker questions you're never left with nothing to talk about!</p>
      </div>
      <div>
        <h4>First h4</h4>
        <p><a href="#">Link 2</a></p>
        <h4>Second h4</h4>
        <p><a href="#">Link 1</a></p>
      </div>
    </main>
```

Thanks!

**Comment by aviflombaum** [comment]
Addressed in https://github.com/learn-co-curriculum/icebreakers-homepage-html-lab/commit/bc51ee4f484650c5cd915f1767565734af78af6c
